import Head from "next/head"
import Aadhar from "../components/Aadhar"
import Footer from "../components/Footer"
import HeroSection from "../components/HeroSection"
import Navbar from "../components/Navbar"

export default function Home() {
  return (
    <div
      style={{
        background: "url(./images/leaves.svg)",
        backgroundPosition: "center",
        backgroundSize: "contain",
        backgroundRepeat: "repeat-y",
      }}
      className="w-full min-h-screen bg-primary"
    >
      <Head>
        <title>E-Ganana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Navbar */}
      <main className="bg-primary w-full min-h-screen flex flex-col ">
        <Navbar />
        <div className="flex flex-1 flex-col h-fit space-y-6 items-center justify-center">
          {/* <HeroSection /> */}
          <Aadhar />
        </div>

        <Footer />
      </main>
    </div>
  )
}
